"""timestamp in news post

Revision ID: 19de8b2ee5e1
Revises: b912575521ba
Create Date: 2024-05-18 17:22:47.583560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19de8b2ee5e1'
down_revision: Union[str, None] = 'b912575521ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_post', sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('news_post', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_post', sa.Column('date', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('news_post', 'created_date')
    # ### end Alembic commands ###
