"""empty message

Revision ID: 25f4a6ab4957
Revises: 87e83187bbf1
Create Date: 2024-05-08 18:54:25.074188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f4a6ab4957'
down_revision: Union[str, None] = '87e83187bbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('goalID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goalID'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_id'), 'habit', ['id'], unique=False)
    op.create_index(op.f('ix_goal_id'), 'goal', ['id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_goal_id'), table_name='goal')
    op.drop_index(op.f('ix_habit_id'), table_name='habit')
    op.drop_table('habit')
    # ### end Alembic commands ###
