"""empty message

Revision ID: 30a43cd097ae
Revises: 49b2b0c7b67f
Create Date: 2024-05-12 18:24:17.545438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a43cd097ae'
down_revision: Union[str, None] = '49b2b0c7b67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('habit_goalID_fkey', 'habit', type_='foreignkey')
    op.create_foreign_key(None, 'habit', 'goal', ['goalID'], ['id'], ondelete='CASCADE')
    op.drop_constraint('habit_track_habitID_fkey', 'habit_track', type_='foreignkey')
    op.create_foreign_key(None, 'habit_track', 'habit', ['habitID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit_track', type_='foreignkey')
    op.create_foreign_key('habit_track_habitID_fkey', 'habit_track', 'habit', ['habitID'], ['id'])
    op.drop_constraint(None, 'habit', type_='foreignkey')
    op.create_foreign_key('habit_goalID_fkey', 'habit', 'goal', ['goalID'], ['id'])
    # ### end Alembic commands ###
