"""empty message

Revision ID: 538ca0d494ee
Revises: 3f86149adddd
Create Date: 2024-05-09 11:03:21.904481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538ca0d494ee'
down_revision: Union[str, None] = '3f86149adddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_track', sa.Column('is_checked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_track', 'is_checked')
    # ### end Alembic commands ###
