"""del pwd confirmation col

Revision ID: eb1dff14178a
Revises: 4b0fa0bcd16d
Create Date: 2024-05-05 12:46:50.601787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1dff14178a'
down_revision: Union[str, None] = '4b0fa0bcd16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passwordConfirm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwordConfirm', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
